apiVersion: batch/v1
kind: CronJob
metadata:
  name: ai-log-anomaly-detector
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: anomaly-detector
            image: afs/ai-anomaly-detector:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
